### ISSUE TITLE
Demo broken

### ISSUE THREAD

**Issue by justgage** [elm-community/elm-datepicker#14]
Looks like the demo page is broken.

**Comment by bbqbaron** [comment]
I removed it because it was now gone from the old maintainer's github. Sorry, where do you still see a reference to it?

**Comment by justgage** [comment]
On the main package page: http://package.elm-lang.org/packages/Bogdanp/elm-datepicker/latest

**Comment by bbqbaron** [comment]
Ah! That's actually the old, pre-conversion version of the package, which I don't think they'll unpublish in order not to break existing installs. I think that demo page is just a 404, and not broken due to the conversion. [Here](http://package.elm-lang.org/packages/elm-community/elm-datepicker/latest) is the new page.
