### ISSUE TITLE
Support for multiple date formats

### ISSUE THREAD

**Issue by caskolkm** [elm-community/elm-datepicker#15]
The date format can be configured, although you can still not enter a dutch formatted date.

**Comment by bbqbaron** [comment]
I see what you mean. It looks like we're using the vanilla Elm [Date.fromString](http://package.elm-lang.org/packages/elm-lang/core/5.1.1/Date#fromString) to parse dates. What if I add a settings key `parser : String -> Result String Date`, so that the user can provide whatever localized parser they like? The repo is quite minimal, so I don't know if it should ship with all possible date input formats.

**Comment by caskolkm** [comment]
Totally agreed with that.
