### ISSUE TITLE
Set isDisabled based on current date

### ISSUE THREAD

**Issue by A5308Y** [elm-community/elm-datepicker#32]
Currently `isDisabled` is a user provided function taking any date as its last argument. If dates are to be disabled in relation to the current date, the user has to provide the current date to `isDisabled` themselves.

This is in spite of the datepicker "knowing" of the current date:
```elm
    case msg of
        CurrentDate date ->
            prepareDates (pickedDate ?> date) { model | today = date } ! []
```

I think it is a common use case to disable past dates. Picking dates for appointments, due dates, or something similar only makes sense for the future.

Allowing users to use the datepicker's `today` value for disabling pickable dates would remove this "forced duplication" of `today` and prevent users from having to use a command to get the current date, which might make the datepicker more accessible for users new to Elm.

I see two ways this could be done:

1. Passing `today` to `isDisabled` in addition to `date`
This might be a bit confusing to users that only want to disable dates based on its values though (disable weekends for example).

2. Allow to disabled past dates in the settings
The other option I see is to disable past dates by providing a new option for the settings. This might be a too specific use case to warrant a new parameter for the settings, though. Another problem I see is that for some use cases the current day should be disabled, while it shouldn't be for others. There are probably also valid cases for disabling dates older than a week from now. So this option might not be flexible enough.

**Comment by A5308Y** [comment]
@bbqbaron Is this clear enough?

**Comment by bbqbaron** [comment]
I think so! Also see in-progress #36, which could change the meaning of `today` and thus affect any possible implementation of a PR.

**Comment by fedragon** [comment]
Hello @bbqbaron is there any update on this? I would also need to disable past dates in datepickers...

**Comment by bbqbaron** [comment]
No PRs have arrived yet. Personally, I might vote not to implement this as a feature; it would cause a major version release to add a convenience. Convenience is great, but API churn isn't :). Since I _believe_ this repo is being retired by elm-community for 0.19, we may not have another major anyway.

What do you think about just using the current date in your implementation of `isDisabled`? The issue was opened because the opener would prefer not to have to do that, but it certainly seems feasible.

Sorry if that seems unhelpful! By claiming that a problem can be solved without a new feature, I certainly don't mean to say "Go away!" :)

**Comment by fedragon** [comment]
Hi @bbqbaron,
no worries, I understand your point of view :) 
I can definitely use `Date.now` in `isDisabled`, I was just hoping to be able to do it without managing`Task`s explicitly. Thanks anyway!
