### ISSUE TITLE
Picked date is not visible if set programmatically outside the datepicker

### ISSUE THREAD

**Issue by julianjelfs** [elm-community/elm-datepicker#43]
I am constructing a date range component from two date pickers and if I set a far future date in the start date picker, I then check if the start date is now > the current end date and change the end date if it needs to be changed. 

This works fine, and the end date picker ends up displaying the correct date in its input control, but if I then focus the end date picker, the date picker ui may be displaying the wrong month. i.e. it does not seem to automatically be displaying the month that matches the selected date.  

I think this is because ```focused``` is still set to whatever value the date picker was initialised with. When we pick a date by clicking on the calendar, ```focused``` is set to Nothing, but if I just change the pickedDate programmatically it has no effect on ```focused```. 

Not sure what the best solution to this is. Do you think my diagnosis is correct and can you think of an obvious solution?

**Comment by julianjelfs** [comment]
Seems like the fundamental problem here is that if I mouse-pick a date, the datepicker is notified via Pick and takes the required action, but if I programmatically pick a date, the datepicker knows nothing about it and therefore has no opportunity to take that action. 

Seems that this would be fixed by reintroducing the helper ```pick``` function that just exposes the Pick Msg. That way I could call the update function when I change the date. 

Pretty sure that would work but it seems a bit weird. Like we have two important bits of state, the focused date and the selected date and the datepicker manages one of them and I manage the other one.

**Comment by bbqbaron** [comment]
`pick` does seem weird, because you'd call `pick` and just pass the same date into the view. Seems to bifurcate state for no reason. Let's say the options out loud, even the dumb ones, so maybe something will present itself.

* You have to call `pick` and also pass the date to the view. I don't like this.
* _Also_ lift the focused date up and make the user store that too. Not a fan.
* Keep a last-picked-date in state, and if the date passed to the view is not the same, ignore `focused` and `inputText` in favor of this value. Will act oddly if they programmatically go from date A to B to A.
* Give up, keep state internally, expand API, think about why the pattern doesn't work here.

I wondered why we're the only people thinking about this, so I looked at the [other, fancier picker](https://github.com/abadi199/datetimepicker/blob/3.0.0/src/DateTimePicker.elm#L740) a little. (Why are there two in Elm?). 

It seems like they solve it by ignoring the current date passed into the view, and just  showing their internal state's `titleDate`. I'm not positive I have that right, but `currentDate` certainly doesn't seem to be used. I haven't proven it in a demo, but it seems like their picker would not respond the way you'd expect to a programmatic date change either, if that's any consolation? :P

**Comment by julianjelfs** [comment]
Tricky isn't it? I was going to say that I favoured the third approach I think. So if the inbound date in the view fn is not the date that was last mouse-picked, then I know it has been changed programmatically and I should focus on that date. Is that what you meant? Can you explain the downside of that one? Seems appealing because it placed no burden on users of the component who *do not* want to programmatically modify the date (maybe the majority).

**Comment by bbqbaron** [comment]
I think the downside is that caching the date I last picked isn't the same as knowing when the date has been changed. The scenario would be:

1. Pick date A
2. Programmatically pick date B
3. Programmatically pick A again
4. Suddenly any focus or input values "removed" (but really just obscured) by switching to B would be resurrected, right?

It sees like a corner case, but it's a bug that, if noticed, would be hard to eradicate.

**Comment by julianjelfs** [comment]
Yes I see. Very nasty. Feels like it probably wouldn't be a problem in practice but it would be a horrible feeling deliberately building in a bug. 

Perhaps option 1 is the best of a bad bunch then. At least it still only matters for users who need to set the date programmatically.

**Comment by bbqbaron** [comment]
Okay, I think I agree with you. Imminent merge coming that just reinstates `pick : Maybe Date -> Msg`, with an explanatory note that it's for simulating a user choice action and will change the focused date, etc.

**Comment by bbqbaron** [comment]
And we're up.

**Comment by Augustin82** [comment]
Hi @bbqbaron! Sorry to post in a closed issue, but I'm having trouble using `pick` in my use case.
The (simplified) use case is this: I receive a `startDate` via flags. I display it to my users. When they click "Edit", I `init` the DatePicker. At that point, the DatePicker's focused date goes from '92 to `today`. The thing is: I want it to go to `startDate` instead. To do that, I'd need to somehow react to my `SetDatePicker datePickerMsg` (but only the one caused by `init`!) and then manually update my DatePicker state with `pick` and my `startDate`. I see no way of doing that.

The only solution I'd see for now would be to roll out my own `DatePicker.init`, replacing `Task.perform CurrentDate Date.now` with `Task.perform CurrentDate (Task.succeed startDate)`. However, since Msg is opaque and CurrentDate is not exposed, I cannot.
This seems to me to indicate that `init` should probably take an `initialDate : Maybe Date` or something.

What do you think? Am I missing something? Would you like me to write a PR of what I have in mind?

Thanks!

**Comment by Augustin82** [comment]
Hi! It would probably work, but I'm weary of "probably" =P Also, in my app, I actually instanciate many pickers (2 per "event", with the user creating as many events, dynamically, as they please). I'd really need to be able to set the "focused" date in `init` since, after all, I do want to init my datepicker with this date right from the start. Note that, since I'm using the concept of "today" for disabling dates, I could also init with today and skip the `CurrentDate` message entirely. Maybe expose an alternate `init`, then?

Something like
```elm
initWithDates : Maybe Date -> Date -> DatePicker.DatePicker
initWithDate focused today =
    ...
```

**Comment by bbqbaron** [comment]
@Augustin82 could you have a look at #50? Thoughts? Preferences?

**Comment by Augustin82** [comment]
@bbqbaron sorry for the long delay =/
Thanks for your thoughts on the problem. I'm not 100% sure of how you'd use your proposal: would that mean I'd use it like that?
```elm
myInitPicker startDate today =
    initWithState { defaultState | focused = Just selected, today = today }
```

It could work, but as you said in the PR, I wouldn't want to use the command returned (I think?).

Sorry if I'm not making sense =) Can I do anything to help?

**Comment by bbqbaron** [comment]
Sorry for the counter-long delay!

(`List.map (flip (++) "Sorry for the delay!\n") prPosts`)

> It could work, but as you said in the PR, I wouldn't want to use the command returned (I think?).

Is this not OK? It's true that you wouldn't want to use it, but is that a problem?

You certainly can help; thanks for offering. Do you have perhaps a different solution/PR in mind?

**Comment by Augustin82** [comment]
Sorry for taking more than ~~a few days~~ ~~a week~~ a month to answer.

I've gone through the code with a fresh mind, and I guess it would work.

I'm thinking that we may need a "nicer" function to allow a user to create a custom state, but obviously it's doable as it stands.

For information, what problems did you see with my previous suggestion? I admit to having limited vision in terms of the requirements for a public API, so I may be missing something obvious =)
```elm
initWithDates : Maybe Date -> Date -> DatePicker.DatePicker
initWithDate focused today =
    ...
```

Many thanks!

**Comment by bbqbaron** [comment]
Oh, sorry, I didn't so much _object_ to your suggestion as was just suggesting something that might already work without changing the API at all. Since I _believe_ Elm is going to stop hosting a community datepicker as of 0.19, I'm actually pretty laissez-faire about adding functions that don't cause major bumps, this being an example.

As a larger philosophical issue, something starts to feel strange when we need to expose multiple init functions for a potentially exponential number of situations. That said, I'm also not a very good API designer, so please don't take me as an authority :).

We in fact added an `initWithDates` in #53, so it would only be fair for me to accept a PR for yours as well!

**Comment by Augustin82** [comment]
I hadn't seen `initFromDate`. I don't really understand why that function assumes that the default selected date would be "today".
I believe my proposal covered more use cases for only a marginal increase in complexity.

I'll try and find the time to propose a PR later today =)

**Comment by Augustin82** [comment]
Done in PR #57!
