### ISSUE TITLE
Readonly attribute for input

### ISSUE THREAD

**Issue by bardt** [elm-community/elm-datepicker#48]
I found a case I could not achieve with current customization options. The input for date picker should be read only in my case. It is needed to prevent user input, but to give a choice of some predefined range of dates. It is commonly done with `readonly` attribute set on the input.

I've seen the `required` setting, and in my opinion `readonly` should be similar. But for a more general solution, I propose a list of additional input attributes as a settings option.

**Comment by bbqbaron** [comment]
Yeah, I'm inclined to agree with you! Back when I took over the repo, I suggested something similar and was convinced that too many attributes lets the user shoot themselves in the foot.

However, I'm since convinced that I/we were right in the first place. I'd happily merge such a PR; I guess it wouldn't even have to be a major upgrade. Should be pretty straightforward, I imagine.

**Comment by bardt** [comment]
@bbqbaron just to make it clear. Are you approving my plan about adding attributes list as a settings option? 

It looks a major version bump, because it will change public api.

**Comment by bardt** [comment]
@bbqbaron the PR is above. Just to attract your attention)
