### ISSUE TITLE
Date picker doesn't pick on "child" pages

### ISSUE THREAD

**Issue by brett-mcgirr** [elm-community/elm-datepicker#55]
I have an example that has the date picker in a child model (for a SPA) and the date picker shows but it doesn't register dates being clicked.

It's quite possible that I've initialised something incorrectly but it could also be a bug.

https://ellie-app.com/48DbNNHP9FZa1/0

Thanks for the help!

**Comment by bbqbaron** [comment]
That is pretty peculiar. I've taken a cursory look; it seems like an event timing issue. If you tap a trackpad lightning fast, the child page picks; otherwise it doesn't. It smells like it's doing:

* `mousedown`
* `blur`
* `mouseup`

At which point, I have to hypothesize, no click can occur on the element, since it's gone.

What's strange--and may just be an artifact of Elm--is that it seems to only affect the child picker. Something about the type indirection may change where the event listeners ultimately end up? That's a wild guess, but it does seem like the structure of your code determines the behavior. Will check back in.

**Comment by BrettMcGirr** [comment]
Hi, I've figured out what I was doing wrong. I was attaching the current model to the msg to help with types in a case .. of statement but that meant that certain msgs wouldn't have an updated model to work with.

Here's a fixed version of the code. https://ellie-app.com/nyQgnxc9Sa1/0

Thanks for the help!
