### ISSUE TITLE
Upgrade to 0.19?

### ISSUE THREAD

**Issue by JDemler** [elm-community/elm-datepicker#87]
Currently `elm-datepicker` is not ported to elm 0.19.

Are there any plans for doing so?

**Comment by bbqbaron** [comment]
Last I knew, the Elm community was not planning to maintain any official datepicker as of 0.19; they didn't think it was a particularly "core" thing to have, which I can totally understand. I've been keeping this alive but treating it as near-deprecated, at least in its current form.

However! There's certainly no reason this can't be...forked?...to a 0.19-compatible privately maintained library, for sure. It sounds like there's interest. I'm actually kind of an OSS-practices newbie, so do you have suggestions on the best idiom? I assume we can't move the repo out of `elm-community`, since < 0.19 still exists of course, but we also can't publish an 0.19 branch from here. Does that sound like a reason to fork?

**Comment by JDemler** [comment]
FYI: I am currently porting this package myself. It will depend upon `justinmimbs/date`.

Will probably be done by the end of the week. Maybe sooner.

**Comment by JDemler** [comment]
PR #88 provides the port.
I think `elm-community` is the wrong place to host this now. (Due to the external dependency)

If I see it correctly the current maintainer is @bbqbaron. Do you want to keep maintaining this package?
Otherwise CurrySoftware would offer to take over that responsibility.

**Comment by bbqbaron** [comment]
I'd be very pleased to have you do it. My Elm work has since ended and I'm honestly not very good at the visual parts of UX. Thanks so much for offering! As a matter of ceremony, I'm guessing I shouldn't just unilaterally transfer admin rights. My last contact was @eeue56 -- do you mind talking to him? I think he blesses it.

**Comment by JDemler** [comment]
I spoke with @eeue56. We agreed, that `elm-datepicker` for elm 0.19 will move to [CurrySoftware/elm-datepicker](https://github.com/CurrySoftware/elm-datepicker).

Please update the readme to reflect this change.

**Comment by eeue56** [comment]
And open a PR against the manifesto to make the correct change

**Comment by bbqbaron** [comment]
[Opened](https://github.com/elm-community/Manifesto/pull/90). README updated.
